services:
  - type: web
    name: final-asset
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_TIMEZONE
        value: Asia/Dubai
      - key: APP_KEY
        generateValue: true

databases:
  - name: finalassetdb
    plan: free
    databaseName: final_asset
    user: finalassetuser
