services:
  - type: web
    name: final-asset
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan migrate --force && php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_TIMEZONE
        value: Asia/Dubai

  - type: worker
    name: final-asset-scheduler
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan schedule:work
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_TIMEZONE
        value: Asia/Dubai

databases:
  - name: finalassetdb
    plan: free
    databaseName: final_asset
    user: finalassetuser
